apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-reset-mon-job
  namespace: rook-ceph # namespace:cluster
  labels:
    app: ceph-toolbox-job
spec:
  template:
    spec:
      initContainers:
      - name: config-init
        image: rook/ceph:master
        command: ["/usr/local/bin/toolbox.sh"]
        args: ["--skip-watch"]
        imagePullPolicy: IfNotPresent
        env:
        - name: ROOK_CEPH_USERNAME
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: ceph-username
        - name: ROOK_CEPH_SECRET
          valueFrom:
            secretKeyRef:
              name: rook-ceph-mon
              key: ceph-secret
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-config
        - name: mon-endpoint-volume
          mountPath: /etc/rook
      containers:
      - name: script
        image: rook/ceph:master
        command:
        - "bash"
        - "-c"
        - |
          # Modify this script to run any ceph, rbd, radosgw-admin, or other commands that could
          # be run in the toolbox pod. The output of the commands can be seen by getting the pod log.

          # Variables to be set more dynamically
          mon_to_reset=a

          monmap_path=/tmp/monmap
          ceph-mon \
            --fsid=$ROOK_CEPH_FSID \
            --keyring=/etc/ceph/keyring-store/keyring \
            --log-to-stderr=true \
            --err-to-stderr=true \
            --mon-cluster-log-to-stderr=true \
            --log-stderr-prefix=debug \
            --default-log-to-file=false \
            --default-mon-cluster-log-to-file=false \
            --mon-host=$ROOK_CEPH_MON_HOST \
            --mon-initial-members=$ROOK_CEPH_MON_INITIAL_MEMBERS \
            --id=$mon_to_reset \
            --foreground \
            --setuser-match-path=/var/lib/ceph/mon/ceph-$mon_to_reset/store.db \
            --extract-monmap=$monmap_path

          # review the contents of the monmap
          printf "\n\nORIGINAL MONMAP:\n\n"
          monmaptool --print $monmap_path

          # remove the other mons from the monmap
          printf "\n\n REMOVING b and c from the monmap \n\n"
          monmaptool --rm b $monmap_path
          monmaptool --rm c $monmap_path
          printf "Done removing b and c from the monmap \n\n"

          # inject the modified monmap into the good mon, by pasting
          # the ceph mon command and adding the
          # `--inject-monmap=${monmap_path}` flag, like this
          ceph-mon \
            --fsid=$ROOK_CEPH_FSID \
            --keyring=/etc/ceph/keyring-store/keyring \
            --log-to-stderr=true \
            --err-to-stderr=true \
            --mon-cluster-log-to-stderr=true \
            --log-stderr-prefix=debug \
            --default-log-to-file=false \
            --default-mon-cluster-log-to-file=false \
            --mon-host=$ROOK_CEPH_MON_HOST \
            --mon-initial-members=$ROOK_CEPH_MON_INITIAL_MEMBERS \
            --id=$mon_to_reset \
            --foreground \
            --setuser-match-path=/var/lib/ceph/mon/ceph-$mon_to_reset/store.db \
            --inject-monmap=$monmap_path

          printf "\n\nFINAL MONMAP:\n\n"
          monmaptool --print $monmap_path
        env:
        - name: ROOK_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ROOK_CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: ROOK_CEPH_MON_INITIAL_MEMBERS
          valueFrom:
            secretKeyRef:
              key: mon_initial_members
              name: rook-ceph-config
        - name: ROOK_CEPH_FSID
          valueFrom:
            secretKeyRef:
              key: fsid
              name: rook-ceph-mon
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-config
          readOnly: true
        - mountPath: /var/lib/ceph/mon/ceph-a
          name: ceph-daemon-data
      volumes:
      - name: mon-endpoint-volume
        configMap:
          name: rook-ceph-mon-endpoints
          items:
          - key: data
            path: mon-endpoints
      - hostPath:
          path: /var/lib/rook/mon-a/data
          type: ""
        name: ceph-daemon-data
      - name: ceph-config
        emptyDir: {}
      restartPolicy: Never
