#################################################################################################################
# Define the settings for the rook-ceph cluster with common settings for a production cluster on top of cloud instances.
# At least three nodes are required in this example. See the documentation for more details on storage settings available.

# For example, to create the cluster:
#   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
#   kubectl create -f cluster-on-pvc.yaml
#################################################################################################################
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph # namespace:cluster
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    volumeClaimTemplates:
      spec:
        storageClassName: ibmc-vpc-block-10iops-tier
        resources:
          requests:
            storage: 10Gi
  cephVersion:
    #image: registry.redhat.io/rhceph/rhceph-8-rhel9@sha256:f9aee41d14400391965766dd3a8abf544f0303d06c4b6462ac7f1645bfe2db71
    image: quay.io/brgardne/ceph:19.2.1-222.el9cp-debug-1
  cleanupPolicy:
    sanitizeDisks: {}
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  crashCollector: {}
  csi:
    cephfs:
      kernelMountOptions: ms_mode=prefer-crc
    readAffinity:
      enabled: true
    skipUserCreation: true
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    managePodBudgets: true
  labels:
    exporter:
      rook.io/managedBy: ocs-storagecluster
    mgr:
      odf-resource-profile: ""
    mon:
      odf-resource-profile: ""
    monitoring:
      rook.io/managedBy: ocs-storagecluster
    osd:
      odf-resource-profile: ""
  logCollector:
    enabled: true
    maxLogSize: 500Mi
    periodicity: daily
  cephConfig:
    global:
      debug_ms: "1"
      debug_rgw: "20"
      mon_max_pg_per_osd: "1000"
      mon_target_pg_per_osd: "200"
  mgr:
    count: 2
    modules:
      - enabled: true
        name: pg_autoscaler
        settings: {}
      - enabled: true
        name: balancer
        settings: {}
      - name: rook
        settings: {}
  monitoring:
    enabled: true
    interval: 30s
  network:
    connections:
      requireMsgr2: true
    #provider: multus
    #selectors:
    #  cluster: openshift-storage/private-net
    #  public: openshift-storage/public-net
  placement:
    all:
      #nodeAffinity:
      #  requiredDuringSchedulingIgnoredDuringExecution:
      #    nodeSelectorTerms:
      #      - matchExpressions:
      #          - key: cluster.ocs.openshift.io/openshift-storage
      #            operator: Exists
      tolerations:
        - effect: NoSchedule
          key: node.ocs.openshift.io/storage
          operator: Equal
          value: "true"
    #arbiter:
    #  tolerations:
    #    - effect: NoSchedule
    #      key: node-role.kubernetes.io/master
    #      operator: Exists
    mon:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - rook-ceph-mon
            topologyKey: kubernetes.io/hostname
  priorityClassNames:
    crashcollector: system-node-critical
    exporter: system-node-critical
    mgr: system-node-critical
    mon: system-node-critical
    osd: system-node-critical
  #resources:
  #  crashcollector:
  #    limits:
  #      cpu: 100m
  #      memory: 60Mi
  #    requests:
  #      cpu: 100m
  #      memory: 60Mi
  #  exporter:
  #    limits:
  #      cpu: 50m
  #      memory: 128Mi
  #    requests:
  #      cpu: 50m
  #      memory: 50Mi
  #  mgr:
  #    limits:
  #      cpu: "2"
  #      memory: 3Gi
  #    requests:
  #      cpu: "1"
  #      memory: 1536Mi
  #  mon:
  #    limits:
  #      cpu: "1"
  #      memory: 2Gi
  #    requests:
  #      cpu: "1"
  #      memory: 2Gi
  security:
    keyRotation:
      enabled: false
      schedule: "@weekly"
  storage:
    allowOsdCrushWeightUpdate: true
    flappingRestartIntervalHours: 24
    storageClassDeviceSets:
      - count: 3
        name: ocs-deviceset-ibm-0
        placement:
          topologySpreadConstraints:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
        preparePlacement:
          topologySpreadConstraints:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rook-ceph-osd
                      - rook-ceph-osd-prepare
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
        #resources:
        #  limits:
        #    cpu: "2"
        #    memory: 5Gi
        #  requests:
        #    cpu: "2"
        #    memory: 5Gi
        tuneFastDeviceClass: true
        volumeClaimTemplates:
          - metadata:
              annotations:
                crushDeviceClass: ssd
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              storageClassName: ibmc-vpc-block-10iops-tier
              volumeMode: Block
