# This example is for Ceph v20 and above only
# The CephBlockPool must be created before the CephNVMeOFGateway,
# provided in the example nvmeof-pool.yaml.
apiVersion: ceph.rook.io/v1
kind: CephNVMeOFGateway
metadata:
  name: nvmeof
  namespace: rook-ceph # namespace:cluster
spec:
  image: quay.io/ceph/nvmeof:1.5
  pool: nvmeofpool
  group: mygroup
  instances: 1
  hostNetwork: false
