apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rook-ceph-mon
        app.kubernetes.io/component: cephclusters.ceph.rook.io
        app.kubernetes.io/created-by: rook-ceph-operator
        app.kubernetes.io/instance: a
        app.kubernetes.io/managed-by: rook-ceph-operator
        app.kubernetes.io/name: ceph-mon
        app.kubernetes.io/part-of: my-cluster
        ceph_daemon_id: a
        ceph_daemon_type: mon
        mon: a
        mon_cluster: rook-ceph
        mon_daemon: "true"
        rook.io/operator-namespace: rook-ceph
        rook_cluster: rook-ceph
      name: rook-ceph-mon-a
      namespace: rook-ceph
    spec:
      clusterIP: 10.103.106.98
      clusterIPs:
        - 10.103.106.98
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: tcp-msgr1
          port: 6789
          protocol: TCP
          targetPort: 6789
        - name: tcp-msgr2
          port: 3300
          protocol: TCP
          targetPort: 3300
      selector:
        app: rook-ceph-mon
        ceph_daemon_id: a
        mon: a
        mon_cluster: rook-ceph
        rook_cluster: rook-ceph
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rook-ceph-mon
        app.kubernetes.io/component: cephclusters.ceph.rook.io
        app.kubernetes.io/created-by: rook-ceph-operator
        app.kubernetes.io/instance: b
        app.kubernetes.io/managed-by: rook-ceph-operator
        app.kubernetes.io/name: ceph-mon
        app.kubernetes.io/part-of: my-cluster
        ceph_daemon_id: b
        ceph_daemon_type: mon
        mon: b
        mon_cluster: rook-ceph
        mon_daemon: "true"
        rook.io/operator-namespace: rook-ceph
        rook_cluster: rook-ceph
      name: rook-ceph-mon-b
      namespace: rook-ceph
    spec:
      clusterIP: 10.105.180.252
      clusterIPs:
        - 10.105.180.252
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: tcp-msgr1
          port: 6789
          protocol: TCP
          targetPort: 6789
        - name: tcp-msgr2
          port: 3300
          protocol: TCP
          targetPort: 3300
      selector:
        app: rook-ceph-mon
        ceph_daemon_id: b
        mon: b
        mon_cluster: rook-ceph
        rook_cluster: rook-ceph
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: rook-ceph-mon
        app.kubernetes.io/component: cephclusters.ceph.rook.io
        app.kubernetes.io/created-by: rook-ceph-operator
        app.kubernetes.io/instance: c
        app.kubernetes.io/managed-by: rook-ceph-operator
        app.kubernetes.io/name: ceph-mon
        app.kubernetes.io/part-of: my-cluster
        ceph_daemon_id: c
        ceph_daemon_type: mon
        mon: c
        mon_cluster: rook-ceph
        mon_daemon: "true"
        rook.io/operator-namespace: rook-ceph
        rook_cluster: rook-ceph
      name: rook-ceph-mon-c
      namespace: rook-ceph
    spec:
      clusterIP: 10.100.247.25
      clusterIPs:
        - 10.100.247.25
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: tcp-msgr1
          port: 6789
          protocol: TCP
          targetPort: 6789
        - name: tcp-msgr2
          port: 3300
          protocol: TCP
          targetPort: 3300
      selector:
        app: rook-ceph-mon
        ceph_daemon_id: c
        mon: c
        mon_cluster: rook-ceph
        rook_cluster: rook-ceph
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
